deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branches:
      only:
        - gh-pages
  local_dir: docs

before_script:
    - npm install
script:
    - npm run build
language: node_js
node_js:
    - 10.16.3