deploy:
  provider: pages
  skip_cleanup: true
  github_token: 15d8307ef76d0a1449a33e09c407299dc9f79bca
  on:
    branches:
      only:
        - gh-pages
  local_dir: docs

before_script:
    - npm install
script:
    - npm run build
language: node_js
node_js:
    - 10.16.3