deploy:
  provider: pages
  skip_cleanup: true
  github_token: 765f348dafebf576e7d68721e34cd8b0f6c01f7d
  on:
    branches:
      only:
        - gh-pages
  local_dir: docs

before_script:
    - npm install
script:
    - npm run build
language: node_js
node_js:
    - 10.16.3